In [75]:
import requests
from bs4 import BeautifulSoup
import time

In [76]:
#iterate the pages and generate url for them
base_url = "https://www.immoweb.be/en/search/house/for-sale?countries=BE&"
for i in range (1,334):
    new_url = base_url + "page="+ str(i) +"&orderBy=newest"

Locality
Type of property (House/apartment)
Subtype of property (Bungalow, Chalet, Mansion, ...)
Price
Type of sale (Exclusion of life sales)
Number of rooms
Area
Fully equipped kitchen (Yes/No)
Furnished (Yes/No)
Open fire (Yes/No)
Terrace (Yes/No)
If yes: Area
Garden (Yes/No)
If yes: Area
Surface of the land
Surface area of the plot of land
Number of facades
Swimming pool (Yes/No)
State of the building (New, to be renovated, ...)

In [108]:
#work on single adv. 
one_ad = open ("/Users/mselmaesen/Desktop/challenge-collecting-data/one_ad", "w")

url = "https://www.immoweb.be/en/classified/house/for-sale/jodoigne/1370/8948563?searchId=5f6b4b626f5b7"
response = requests.get(url)
print(response.status_code)
if response.ok:
    
    soup = BeautifulSoup(response.text, "lxml")
    price = soup.find("span",{"aria-hidden":"true"})
    print (price)
    print (price.text)
    
    #Locality ----Ankita

    #Type of property (House/apartment)

    prop_types = ["House","Apartment"] 

    prop_subtype = ["Town house","Mansion","Mixed-use building","Pavilion","Villa","Farm house",
                  "Country cottage", "Castle", "Bungalow", "Chalet","Manor house","Exceptional property",
                  "Other property"]
    
    type_prop = soup.find("div",{"class":"classified__header-content"}).find("h1",{"class":"classified__title"})
    
    type_prop = type_prop.text
    
    for i in prop_types:
        print (i)
        if i in type_prop:
            type_prop= i
    
    for j in prop_subtype:
        if j in type_prop:
            subtype_prop = j
        else:
            subtype_prop = "None"
            
        
    house_facades = soup.find("table", {"class" : "classified-table"})
    #print(house_facades)
    

    for table in soup.find_all("table"):
        for td in soup.find_all("th"):
            print (td)
        #print (table)
    #print (soup.find("th"))
    list_a = []
    string = ""
    for th in soup.find_all("th", {"class":"classified-table__header","scope":"row"}):
        string = string + "\n" + str(th)
        #print (th.text)
        
        
        list_a.append(str(th))
    print (list_a)
   

    # Fully equipped kitchen (Yes/No)
    
    
    

    

#Subtype of property (Bungalow, Chalet, Mansion, ...)

#Type of sale (Exclusion of life sales)
#Number of rooms
#Area
#Fully equipped kitchen (Yes/No)
#Furnished (Yes/No)
#Open fire (Yes/No)
#Terrace (Yes/No)
#If yes: Area
#Garden (Yes/No)
#If yes: Area
#Surface of the land
#Surface area of the plot of land
#Number of facades
#Swimming pool (Yes/No)
#State of the building (New, to be renovated, ...)
    #room_num = soup.find()
    
   # country = soup.find('tr', {'id' : "places_countryrow"}).find('td', {'class': 'w2p_fw'})

200
<span aria-hidden="true">€350,000</span>
€350,000
House
Apartment
<th class="classified-table__header" scope="row">Available as of</th>
<th class="classified-table__header" scope="row">
                                    Neighbourhood or locality
                                </th>
<th class="classified-table__header" scope="row">
                                    Building condition
                                </th>
<th class="classified-table__header" scope="row">
                                    Facades
                                </th>
<th class="classified-table__header" scope="row">Outdoor parking spaces</th>
<th class="classified-table__header" scope="row">
                                    Living area
                                </th>
<th class="classified-table__header" scope="row">Kitchen type</th>
<th class="classified-table__header" scope="row">Bedrooms</th>
<th class="classified-table__header" scope="row">
                                        Bedroom 1 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 2 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 3 surface
                                    </th>
<th class="classified-table__header" scope="row">Bathrooms</th>
<th class="classified-table__header" scope="row">Toilets</th>
<th class="classified-table__header" scope="row">Surface of the plot</th>
<th class="classified-table__header" scope="row">Land plot to rear</th>
<th class="classified-table__header" scope="row">Flat land</th>
<th class="classified-table__header" scope="row">Connection to sewer network</th>
<th class="classified-table__header" scope="row">Gas, water &amp; electricity</th>
<th class="classified-table__header" scope="row">Garden surface</th>
<th class="classified-table__header" scope="row">Terrace</th>
<th class="classified-table__header" scope="row">Terrace orientation</th>
<th class="classified-table__header" scope="row">Number of annexes</th>
<th class="classified-table__header" scope="row">Primary energy consumption</th>
<th class="classified-table__header" scope="row">Energy class</th>
<th colspan="2">
<img alt="" class="classified-table__picture" src="https://static.immoweb.be/pics/peb/peb_c.png"/>
</th>
<th class="classified-table__header" scope="row">Reference number of the EPC report</th>
<th class="classified-table__header" scope="row">CO² emission</th>
<th class="classified-table__header" scope="row">
                                Yearly theoretical total energy consumption
                            </th>
<th class="classified-table__header" scope="row">Heating type</th>
<th class="classified-table__header" scope="row">Double glazing</th>
<th class="classified-table__header" scope="row">Planning permission obtained</th>
<th class="classified-table__header" scope="row">Latest land use designation</th>
<th class="classified-table__header" scope="row">Price</th>
<th class="classified-table__header" scope="row">Cadastral income</th>
<th class="classified-table__header" scope="row">Available as of</th>
<th class="classified-table__header" scope="row">
                                    Neighbourhood or locality
                                </th>
<th class="classified-table__header" scope="row">
                                    Building condition
                                </th>
<th class="classified-table__header" scope="row">
                                    Facades
                                </th>
<th class="classified-table__header" scope="row">Outdoor parking spaces</th>
<th class="classified-table__header" scope="row">
                                    Living area
                                </th>
<th class="classified-table__header" scope="row">Kitchen type</th>
<th class="classified-table__header" scope="row">Bedrooms</th>
<th class="classified-table__header" scope="row">
                                        Bedroom 1 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 2 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 3 surface
                                    </th>
<th class="classified-table__header" scope="row">Bathrooms</th>
<th class="classified-table__header" scope="row">Toilets</th>
<th class="classified-table__header" scope="row">Surface of the plot</th>
<th class="classified-table__header" scope="row">Land plot to rear</th>
<th class="classified-table__header" scope="row">Flat land</th>
<th class="classified-table__header" scope="row">Connection to sewer network</th>
<th class="classified-table__header" scope="row">Gas, water &amp; electricity</th>
<th class="classified-table__header" scope="row">Garden surface</th>
<th class="classified-table__header" scope="row">Terrace</th>
<th class="classified-table__header" scope="row">Terrace orientation</th>
<th class="classified-table__header" scope="row">Number of annexes</th>
<th class="classified-table__header" scope="row">Primary energy consumption</th>
<th class="classified-table__header" scope="row">Energy class</th>
<th colspan="2">
<img alt="" class="classified-table__picture" src="https://static.immoweb.be/pics/peb/peb_c.png"/>
</th>
<th class="classified-table__header" scope="row">Reference number of the EPC report</th>
<th class="classified-table__header" scope="row">CO² emission</th>
<th class="classified-table__header" scope="row">
                                Yearly theoretical total energy consumption
                            </th>
<th class="classified-table__header" scope="row">Heating type</th>
<th class="classified-table__header" scope="row">Double glazing</th>
<th class="classified-table__header" scope="row">Planning permission obtained</th>
<th class="classified-table__header" scope="row">Latest land use designation</th>
<th class="classified-table__header" scope="row">Price</th>
<th class="classified-table__header" scope="row">Cadastral income</th>
<th class="classified-table__header" scope="row">Available as of</th>
<th class="classified-table__header" scope="row">
                                    Neighbourhood or locality
                                </th>
<th class="classified-table__header" scope="row">
                                    Building condition
                                </th>
<th class="classified-table__header" scope="row">
                                    Facades
                                </th>
<th class="classified-table__header" scope="row">Outdoor parking spaces</th>
<th class="classified-table__header" scope="row">
                                    Living area
                                </th>
<th class="classified-table__header" scope="row">Kitchen type</th>
<th class="classified-table__header" scope="row">Bedrooms</th>
<th class="classified-table__header" scope="row">
                                        Bedroom 1 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 2 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 3 surface
                                    </th>
<th class="classified-table__header" scope="row">Bathrooms</th>
<th class="classified-table__header" scope="row">Toilets</th>
<th class="classified-table__header" scope="row">Surface of the plot</th>
<th class="classified-table__header" scope="row">Land plot to rear</th>
<th class="classified-table__header" scope="row">Flat land</th>
<th class="classified-table__header" scope="row">Connection to sewer network</th>
<th class="classified-table__header" scope="row">Gas, water &amp; electricity</th>
<th class="classified-table__header" scope="row">Garden surface</th>
<th class="classified-table__header" scope="row">Terrace</th>
<th class="classified-table__header" scope="row">Terrace orientation</th>
<th class="classified-table__header" scope="row">Number of annexes</th>
<th class="classified-table__header" scope="row">Primary energy consumption</th>
<th class="classified-table__header" scope="row">Energy class</th>
<th colspan="2">
<img alt="" class="classified-table__picture" src="https://static.immoweb.be/pics/peb/peb_c.png"/>
</th>
<th class="classified-table__header" scope="row">Reference number of the EPC report</th>
<th class="classified-table__header" scope="row">CO² emission</th>
<th class="classified-table__header" scope="row">
                                Yearly theoretical total energy consumption
                            </th>
<th class="classified-table__header" scope="row">Heating type</th>
<th class="classified-table__header" scope="row">Double glazing</th>
<th class="classified-table__header" scope="row">Planning permission obtained</th>
<th class="classified-table__header" scope="row">Latest land use designation</th>
<th class="classified-table__header" scope="row">Price</th>
<th class="classified-table__header" scope="row">Cadastral income</th>
<th class="classified-table__header" scope="row">Available as of</th>
<th class="classified-table__header" scope="row">
                                    Neighbourhood or locality
                                </th>
<th class="classified-table__header" scope="row">
                                    Building condition
                                </th>
<th class="classified-table__header" scope="row">
                                    Facades
                                </th>
<th class="classified-table__header" scope="row">Outdoor parking spaces</th>
<th class="classified-table__header" scope="row">
                                    Living area
                                </th>
<th class="classified-table__header" scope="row">Kitchen type</th>
<th class="classified-table__header" scope="row">Bedrooms</th>
<th class="classified-table__header" scope="row">
                                        Bedroom 1 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 2 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 3 surface
                                    </th>
<th class="classified-table__header" scope="row">Bathrooms</th>
<th class="classified-table__header" scope="row">Toilets</th>
<th class="classified-table__header" scope="row">Surface of the plot</th>
<th class="classified-table__header" scope="row">Land plot to rear</th>
<th class="classified-table__header" scope="row">Flat land</th>
<th class="classified-table__header" scope="row">Connection to sewer network</th>
<th class="classified-table__header" scope="row">Gas, water &amp; electricity</th>
<th class="classified-table__header" scope="row">Garden surface</th>
<th class="classified-table__header" scope="row">Terrace</th>
<th class="classified-table__header" scope="row">Terrace orientation</th>
<th class="classified-table__header" scope="row">Number of annexes</th>
<th class="classified-table__header" scope="row">Primary energy consumption</th>
<th class="classified-table__header" scope="row">Energy class</th>
<th colspan="2">
<img alt="" class="classified-table__picture" src="https://static.immoweb.be/pics/peb/peb_c.png"/>
</th>
<th class="classified-table__header" scope="row">Reference number of the EPC report</th>
<th class="classified-table__header" scope="row">CO² emission</th>
<th class="classified-table__header" scope="row">
                                Yearly theoretical total energy consumption
                            </th>
<th class="classified-table__header" scope="row">Heating type</th>
<th class="classified-table__header" scope="row">Double glazing</th>
<th class="classified-table__header" scope="row">Planning permission obtained</th>
<th class="classified-table__header" scope="row">Latest land use designation</th>
<th class="classified-table__header" scope="row">Price</th>
<th class="classified-table__header" scope="row">Cadastral income</th>
<th class="classified-table__header" scope="row">Available as of</th>
<th class="classified-table__header" scope="row">
                                    Neighbourhood or locality
                                </th>
<th class="classified-table__header" scope="row">
                                    Building condition
                                </th>
<th class="classified-table__header" scope="row">
                                    Facades
                                </th>
<th class="classified-table__header" scope="row">Outdoor parking spaces</th>
<th class="classified-table__header" scope="row">
                                    Living area
                                </th>
<th class="classified-table__header" scope="row">Kitchen type</th>
<th class="classified-table__header" scope="row">Bedrooms</th>
<th class="classified-table__header" scope="row">
                                        Bedroom 1 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 2 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 3 surface
                                    </th>
<th class="classified-table__header" scope="row">Bathrooms</th>
<th class="classified-table__header" scope="row">Toilets</th>
<th class="classified-table__header" scope="row">Surface of the plot</th>
<th class="classified-table__header" scope="row">Land plot to rear</th>
<th class="classified-table__header" scope="row">Flat land</th>
<th class="classified-table__header" scope="row">Connection to sewer network</th>
<th class="classified-table__header" scope="row">Gas, water &amp; electricity</th>
<th class="classified-table__header" scope="row">Garden surface</th>
<th class="classified-table__header" scope="row">Terrace</th>
<th class="classified-table__header" scope="row">Terrace orientation</th>
<th class="classified-table__header" scope="row">Number of annexes</th>
<th class="classified-table__header" scope="row">Primary energy consumption</th>
<th class="classified-table__header" scope="row">Energy class</th>
<th colspan="2">
<img alt="" class="classified-table__picture" src="https://static.immoweb.be/pics/peb/peb_c.png"/>
</th>
<th class="classified-table__header" scope="row">Reference number of the EPC report</th>
<th class="classified-table__header" scope="row">CO² emission</th>
<th class="classified-table__header" scope="row">
                                Yearly theoretical total energy consumption
                            </th>
<th class="classified-table__header" scope="row">Heating type</th>
<th class="classified-table__header" scope="row">Double glazing</th>
<th class="classified-table__header" scope="row">Planning permission obtained</th>
<th class="classified-table__header" scope="row">Latest land use designation</th>
<th class="classified-table__header" scope="row">Price</th>
<th class="classified-table__header" scope="row">Cadastral income</th>
<th class="classified-table__header" scope="row">Available as of</th>
<th class="classified-table__header" scope="row">
                                    Neighbourhood or locality
                                </th>
<th class="classified-table__header" scope="row">
                                    Building condition
                                </th>
<th class="classified-table__header" scope="row">
                                    Facades
                                </th>
<th class="classified-table__header" scope="row">Outdoor parking spaces</th>
<th class="classified-table__header" scope="row">
                                    Living area
                                </th>
<th class="classified-table__header" scope="row">Kitchen type</th>
<th class="classified-table__header" scope="row">Bedrooms</th>
<th class="classified-table__header" scope="row">
                                        Bedroom 1 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 2 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 3 surface
                                    </th>
<th class="classified-table__header" scope="row">Bathrooms</th>
<th class="classified-table__header" scope="row">Toilets</th>
<th class="classified-table__header" scope="row">Surface of the plot</th>
<th class="classified-table__header" scope="row">Land plot to rear</th>
<th class="classified-table__header" scope="row">Flat land</th>
<th class="classified-table__header" scope="row">Connection to sewer network</th>
<th class="classified-table__header" scope="row">Gas, water &amp; electricity</th>
<th class="classified-table__header" scope="row">Garden surface</th>
<th class="classified-table__header" scope="row">Terrace</th>
<th class="classified-table__header" scope="row">Terrace orientation</th>
<th class="classified-table__header" scope="row">Number of annexes</th>
<th class="classified-table__header" scope="row">Primary energy consumption</th>
<th class="classified-table__header" scope="row">Energy class</th>
<th colspan="2">
<img alt="" class="classified-table__picture" src="https://static.immoweb.be/pics/peb/peb_c.png"/>
</th>
<th class="classified-table__header" scope="row">Reference number of the EPC report</th>
<th class="classified-table__header" scope="row">CO² emission</th>
<th class="classified-table__header" scope="row">
                                Yearly theoretical total energy consumption
                            </th>
<th class="classified-table__header" scope="row">Heating type</th>
<th class="classified-table__header" scope="row">Double glazing</th>
<th class="classified-table__header" scope="row">Planning permission obtained</th>
<th class="classified-table__header" scope="row">Latest land use designation</th>
<th class="classified-table__header" scope="row">Price</th>
<th class="classified-table__header" scope="row">Cadastral income</th>

In [ ]:
prop_types = ["house", "town house","mansion","apartment","mixed-use building","Pavilion","Villa","Farm house","Country cottage", "Castle", "Bungalow", "Chalet","Manor house","Exceptional property","Other property"]

In [80]:
print (soup.find(id="accordion_a394df75-3eae-4a0f-9b85-f9d1bb9fb1ec"))

None

In [81]:
soup.find (atters = {"class" : "table-block"})

In [104]:
s=""
sd="12"
s = sd + "\n" +"wed"
print (s)

12
wed

In [106]:
print (string)

<th class="classified-table__header" scope="row">Available as of</th>
<th class="classified-table__header" scope="row">
                                    Neighbourhood or locality
                                </th>
<th class="classified-table__header" scope="row">
                                    Building condition
                                </th>
<th class="classified-table__header" scope="row">
                                    Facades
                                </th>
<th class="classified-table__header" scope="row">Outdoor parking spaces</th>
<th class="classified-table__header" scope="row">
                                    Living area
                                </th>
<th class="classified-table__header" scope="row">Kitchen type</th>
<th class="classified-table__header" scope="row">Bedrooms</th>
<th class="classified-table__header" scope="row">
                                        Bedroom 1 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 2 surface
                                    </th>
<th class="classified-table__header" scope="row">
                                        Bedroom 3 surface
                                    </th>
<th class="classified-table__header" scope="row">Bathrooms</th>
<th class="classified-table__header" scope="row">Toilets</th>
<th class="classified-table__header" scope="row">Surface of the plot</th>
<th class="classified-table__header" scope="row">Land plot to rear</th>
<th class="classified-table__header" scope="row">Flat land</th>
<th class="classified-table__header" scope="row">Connection to sewer network</th>
<th class="classified-table__header" scope="row">Gas, water &amp; electricity</th>
<th class="classified-table__header" scope="row">Garden surface</th>
<th class="classified-table__header" scope="row">Terrace</th>
<th class="classified-table__header" scope="row">Terrace orientation</th>
<th class="classified-table__header" scope="row">Number of annexes</th>
<th class="classified-table__header" scope="row">Primary energy consumption</th>
<th class="classified-table__header" scope="row">Energy class</th>
<th class="classified-table__header" scope="row">Reference number of the EPC report</th>
<th class="classified-table__header" scope="row">CO² emission</th>
<th class="classified-table__header" scope="row">
                                Yearly theoretical total energy consumption
                            </th>
<th class="classified-table__header" scope="row">Heating type</th>
<th class="classified-table__header" scope="row">Double glazing</th>
<th class="classified-table__header" scope="row">Planning permission obtained</th>
<th class="classified-table__header" scope="row">Latest land use designation</th>
<th class="classified-table__header" scope="row">Price</th>
<th class="classified-table__header" scope="row">Cadastral income</th>

In [128]:
import re


print (list_a[27])  
pattern2 = ">+\w+\s?\w?+<"
pattern3 = ">+[A-Za-z,;'\"\\s]+[.?!]$+<"
pattern4 = ">+\w+\\s?+\w?+<"
for n in list_a:
    print(re.findall(pattern3,n))
    
print (type(list_a[27]))
print ()

<th class="classified-table__header" scope="row">Heating type</th>

error: nothing to repeat at position 23

In [111]:
print (len (list_a))
print (list_a[0])

33
<th class="classified-table__header" scope="row">Available as of</th>

In [130]:
print (len (list_a[3]))

131

In [132]:
print ([list_a[-1].split()])

[['<th', 'class="classified-table__header"', 'scope="row">Cadastral', 'income</th>']]

In [141]:
element = list_a[-1][49:]
print (element)
print (element[:-5])

Cadastral income</th>
Cadastral income

In [173]:


headers=[]
for n in list_a:
    cut_b = n[49:]
    cut_e = cut_b[:-5]
    headers.append(cut_e)
    
print(headers[-1])

final_headers=[]  

for m in headers:
    str_header = " "
    detect=re.findall("([A-z]+) " ,m )
    print (detect)

    str_header = str_header.join(detect)
    
    final_headers.append(str_header)
    



for header in final_headers:
    print (header)

Cadastral income
['Available', 'as']
['Neighbourhood', 'or']
['Building']
[]
['Outdoor', 'parking']
['Living']
['Kitchen']
[]
['Bedroom']
['Bedroom']
['Bedroom']
[]
[]
['Surface', 'of', 'the']
['Land', 'plot', 'to']
['Flat']
['Connection', 'to', 'sewer']
['water']
['Garden']
[]
['Terrace']
['Number', 'of']
['Primary', 'energy']
['Energy']
['Reference', 'number', 'of', 'the', 'EPC']
[]
['Yearly', 'theoretical', 'total', 'energy']
['Heating']
['Double']
['Planning', 'permission']
['Latest', 'land', 'use']
[]
['Cadastral']
Available as
Neighbourhood or
Building

Outdoor parking
Living
Kitchen

Bedroom
Bedroom
Bedroom


Surface of the
Land plot to
Flat
Connection to sewer
water
Garden

Terrace
Number of
Primary energy
Energy
Reference number of the EPC

Yearly theoretical total energy
Heating
Double
Planning permission
Latest land use

Cadastral

In [184]:
list_bb=[]
list_b = []
for table in soup.find_all("table"):
        for td in soup.find_all("td"):
            list_bb.append(str(td))
print (len(list_bb))   
for i in range(len(list_a)):
    list_b.append(list_bb[i])
    
    print ("*****")
    print (list_bb[i])
print (len(list_b))

204
*****
<td class="classified-table__data">
                                    Immediately
                                </td>
*****
<td class="classified-table__data">
                                    Pietrain
                                </td>
*****
<td class="classified-table__data">
                                    As new
                                </td>
*****
<td class="classified-table__data">
                                    3
                                </td>
*****
<td class="classified-table__data">2</td>
*****
<td class="classified-table__data">
                                    180

                                    <span class="abbreviation">
<span aria-hidden="true">
                                            m²                                        </span>
<span class="sr-only">
                                            square meters
                                        </span>
</span>
</td>
*****
<td class="classified-table__data">
                                    USA hyper equipped
                                </td>
*****
<td class="classified-table__data">3</td>
*****
<td class="classified-table__data">
                                        12

                                        <span class="abbreviation">
<span aria-hidden="true">
                                                m²                                            </span>
<span class="sr-only">
                                                square meters
                                            </span>
</span>
</td>
*****
<td class="classified-table__data">
                                        15

                                        <span class="abbreviation">
<span aria-hidden="true">
                                                m²                                            </span>
<span class="sr-only">
                                                square meters
                                            </span>
</span>
</td>
*****
<td class="classified-table__data">
                                        9

                                        <span class="abbreviation">
<span aria-hidden="true">
                                                m²                                            </span>
<span class="sr-only">
                                                square meters
                                            </span>
</span>
</td>
*****
<td class="classified-table__data">1</td>
*****
<td class="classified-table__data">2</td>
*****
<td class="classified-table__data">
                                        330

                                        <span class="abbreviation">
<span aria-hidden="true">
                                                m²
                                            </span>
<span class="sr-only">
                                                square meters
                                            </span>
</span>
</td>
*****
<td class="classified-table__data">Yes
                                    </td>
*****
<td class="classified-table__data">Yes
                                    </td>
*****
<td class="classified-table__data">
                                        Connected
                                    </td>
*****
<td class="classified-table__data">
                                        Yes
                                    </td>
*****
<td class="classified-table__data">
                                    1600
                                    <span class="abbreviation">
<span aria-hidden="true">
                                            m²
                                        </span>
<span class="sr-only">
                                            square meters
                                        </span>
</span>
</td>
*****
<td class="classified-table__data">Yes
                                </td>
*****
<td class="classified-table__data">
                                    South West
                                </td>
*****
<td class="classified-table__data">2</td>
*****
<td class="classified-table__data">

                                        117

                                        <span class="abbreviation">
<span aria-hidden="true">
                                         kWh/m²
                                    </span>
<span class="sr-only">
                                        kilowatt hour per square meters
                                    </span>
</span>
</td>
*****
<td class="classified-table__data">
                                                                    C
                                                            </td>
*****
<td class="classified-table__data">
                                                                    20180710015175
                                                            </td>
*****
<td class="classified-table__data">
                                                                    Not specified
                                                            </td>
*****
<td class="classified-table__data">
                                    36031 kWh/year
                                </td>
*****
<td class="classified-table__data">
                                Gas
                            </td>
*****
<td class="classified-table__data">
                                Yes
                            </td>
*****
<td class="classified-table__data">Yes
                                </td>
*****
<td class="classified-table__data">
                                    Living area (residential, urban or rural)
                                </td>
*****
<td class="classified-table__data">
<span aria-hidden="true">
                                                                                        € 350,000
                                        </span>
<span class="sr-only">
                                                                                        350000 €
                                        </span>
</td>
*****
<td class="classified-table__data">
<span aria-hidden="true">
                                            € 413
                                        </span>
<span class="sr-only">
                                            413 €
                                        </span>
</td>
33

In [209]:
values = []

for n in list_b:
    cut_b = n[35:]
    
    cut_b=cut_b.replace("</td>", "")
    cut_b=cut_b.replace("abbreviation", "")
    cut_b=cut_b.replace("true", "")
    cut_b=cut_b.replace("sr-only", "")
    cut_b=cut_b.replace("<span class=", "")
    cut_b=cut_b.replace("<span aria-hidden=", "")
    cut_b=cut_b.replace("</span>", "")
    values.append(cut_b)
    
    
    cut_b=cut_b[:130]
    print (cut_b)
    print ("______________________________________________________")
    
#cut_e = cut_b[:-5]
for v in values:
    str_header = " "
    detect=re.findall("([A-z]+)| " ,m )
    print (detect)

                                    Immediately

______________________________________________________

                                    Pietrain

______________________________________________________

                                    As new

______________________________________________________

                                    3

______________________________________________________
2
______________________________________________________

                                    180

                                    "">
"">

______________________________________________________

                                    USA hyper equipped

______________________________________________________
3
______________________________________________________

                                        12

                                        "">
"">

______________________________________________________

                                        15

                                        "">
"">

______________________________________________________

                                        9

                                        "">
"">

______________________________________________________
1
______________________________________________________
2
______________________________________________________

                                        330

                                        "">
"">

______________________________________________________
Yes

______________________________________________________
Yes

______________________________________________________

                                        Connected

______________________________________________________

                                        Yes

______________________________________________________

                                    1600
                                    "">
"">

______________________________________________________
Yes

______________________________________________________

                                    South West

______________________________________________________
2
______________________________________________________


                                        117

                                        "">
"">
______________________________________________________

                                                                    C

______________________________________________________

                                                                    20180710015175

______________________________________________________

                                                                    Not specified

______________________________________________________

                                    36031 kWh/year

______________________________________________________

                                Gas

______________________________________________________

                                Yes

______________________________________________________
Yes

______________________________________________________

                                    Living area (residential, urban or rural)

______________________________________________________

"">
                                                                                        € 350,000

______________________________________________________

"">
                                            € 413

"">

______________________________________________________

In [188]:
selma="selma"
print (selma[:2])

se